import click

@click.command()
@click.argument('heat_file_path', type=click.Path(exists=True, dir_okay=True))
@click.argument('coeff_name', type=click.Path(exists=True, dir_okay=True))
@click.argument('param_name', type=click.Path(exists=True, dir_okay=True))
@click.argument('temp', type=click.FLOAT)
@click.argument('run_steps', type=click.INT)
@click.argument('etol', type=click.FLOAT)
@click.argument('ftol', type=click.FLOAT)
@click.argument('max_iter', type=click.INT)
@click.argument('max_eval', type=click.INT)
def HeatAnalysis(heat_file_path, coeff_name, param_name, temp, run_steps, etol, ftol, max_iter, max_eval):
    click.echo("Generating LAMMPS code input file")
    in_file_path = heat_file_path + "/input/in.heat.HEA"
    lmp_file_path = heat_file_path + "/input/after_relax.data"
# Redirect commands to a file
    with open(in_file_path, 'w') as f:
        f.write("# LAMMPS input script generated by PyLammps\n")
        f.write("# Initialise simulation\n")
        f.write("atom_style     atomic\n")
        f.write("units          metal\n")
        f.write(f"read_data     {lmp_file_path}\n") # can parameterise this

        f.write("# 5 elements of HEA: Ni Co Ti Zr Hf specorder\n")
        f.write("mass           1 58.693\n")
        f.write("mass           2 58.933\n")
        f.write("mass           3 47.867\n")
        f.write("mass           4 91.224\n")
        f.write("mass           5 178.49\n")

        f.write("# Reading snap potential files\n")
        f.write("pair_style     snap\n")
        f.write(f"pair_coeff     * * {coeff_name} {param_name} Ni Co Ti Zr Hf\n") # parameterise
        
        f.write("# Setup standard output\n")
        f.write("variable       avg_lxyz equal (lx+ly+lz)/3.0\n")
        f.write("thermo_style   custom step temp pe pxx pyy pzz density\n")
        f.write("thermo         100\n")

        f.write("# Set up and run MD in NPT ensemble\n")
        f.write("timestep       0.001\n")
        f.write("neighbor       1.0 bin\n")
        f.write("neigh_modify   every 5 delay 0 check yes\n")
        f.write("reset_timestep 0\n")

        f.write(f"dump		    1 all custom 1000 {heat_file_path}output/md_npt_dump.cfg id type x y z\n")  # parameterise for file system
        f.write(f"fix		    1 all npt temp {temp} {temp} 0.1 aniso 0 0 1.0\n")
        Nevery = run_steps//100
        Nrepeat = run_steps//10
        f.write(f"fix		    avg all ave/time {Nevery} {Nrepeat} {run_steps} c_thermo_temp v_avg_lxyz\n") # parameterise
        f.write(f"run		    {run_steps}\n") # parameterise
        f.write("unfix		    1\n")
        f.write("variable       avg_T equal f_avg[1]\n")
        f.write("variable       L equal f_avg[2]\n")
        f.write("variable       L0 equal ${L}\n")
        f.write("print          \"Temp Strain\" file Record_thermal_exp.txt\n")
        f.write("print          \"${avg_T}  0.0\" append Record_thermal_exp.txt\n")
        f.write("unfix          avg")

        f.write("variable	    n loop 14\n") # parametrise
        f.write("label          heat\n")
        f.write("variable       t equal 300+${n}*50\n") # parameterise
        f.write("fix            1 all npt temp ${t} ${t} 0.1 aniso 0 0 1.0\n")
        f.write(f"fix		    avg all ave/time {Nevery} {Nrepeat} {run_steps} c_thermo_temp v_avg_lxyz\n") # parameterise
        f.write(f"run		    {run_steps}\n") # parameterise
        f.write("unfix		    1\n")
        f.write("variable       avg_T equal f_avg[1]\n")
        f.write("variable       L equal f_avg[2]/${L0}-1.0\n")
        f.write("print          \"${avg_T}  ${strain}\" append Record_thermal_exp.txt\n")
        f.write("unfix          avg\n")

        f.write("next           n\n")
        f.write("jump           in.heat.HEA heat")



# running function
if __name__ == '__main__':
    HeatAnalysis()
